name:                ceraxes
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/rajatsharma/ceraxes#readme
license:             BSD3
author:              Rajat Sharma
maintainer:          rajatsharma@github.com
copyright:           2022 Rajat Sharma
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  ceraxes:
    source-dirs:      src
    main:             Main.hs
