name:                ceraxes
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/rajatsharma/ceraxes#readme
license:             BSD3
author:              Rajat Sharma
maintainer:          rajatsharma@github.com
copyright:           2022 Rajat Sharma
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - inflections
  - process
  - directory
  - file-embed
  - filepath
  - optparse-applicative
  - soothsayer
  - bytestring
  - mustache
  - time
  - load-env

# ghc-options:
# - -dynamic

executables:
  ceraxes:
    source-dirs:      src
    main:             Main.hs
